"""협의회 주간 정책브리핑 다이제스트 생성기."""

import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, List, Dict, Tuple
import csv


def get_week_date_range(week_str: str) -> Tuple[str, str]:
    """ISO 주 표기(YYYY-Www)에서 시작/종료 날짜를 반환.

    Args:
        week_str: ISO 주 표기 (예: "2026-W13")

    Returns:
        (시작일, 종료일) 튜플 (YYYY-MM-DD 형식)
    """
    parts = week_str.split("-W")
    year = int(parts[0])
    week = int(parts[1])

    # ISO 8601: 주는 월요일부터 시작
    jan4 = datetime(year, 1, 4)
    week_one_monday = jan4 - timedelta(days=jan4.weekday())
    week_start = week_one_monday + timedelta(weeks=week - 1)
    week_end = week_start + timedelta(days=6)

    return week_start.strftime("%Y-%m-%d"), week_end.strftime("%Y-%m-%d")


def categorize_item(source: str, title: str) -> str:
    """소스와 제목으로부터 섹션을 결정.

    Args:
        source: 데이터 소스
        title: 공고 제목

    Returns:
        섹션명 ("산림", "사회연대경제", "지원사업")
    """
    # 산림 정책 소스
    forest_sources = {"forest_service", "fowi", "kofpi"}
    # 사회연대경제 소스
    sse_sources = {"socialenterprise", "seis", "mois_sse", "coop"}

    if source in forest_sources:
        # 공고성 제목 확인 (공고, 모집, 지원사업 등)
        announcement_keywords = ["공고", "모집", "지원", "신청", "공모", "채용"]
        if any(kw in title for kw in announcement_keywords):
            return "지원사업"
        else:
            return "산림"
    elif source in sse_sources:
        return "사회연대경제"
    else:
        return "지원사업"


def load_form_responses(forms_csv_path: Optional[Path] = None) -> Dict[str, List[str]]:
    """forms/responses.csv에서 회원사 동정 정보 로드.

    Args:
        forms_csv_path: CSV 파일 경로. None이면 forms/responses.csv 시도

    Returns:
        {"회원사명": ["동정내용", ...]} 형태의 딕셔너리
    """
    if forms_csv_path is None:
        forms_csv_path = Path("forms/responses.csv")

    responses = {}
    if not forms_csv_path.exists():
        return responses

    try:
        with open(forms_csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row and "회원사" in row and "내용" in row:
                    company = row["회원사"].strip()
                    content = row["내용"].strip()
                    if company and content:
                        if company not in responses:
                            responses[company] = []
                        responses[company].append(content)
    except Exception as e:
        print(f"Warning: 회원사 동정 로드 실패: {e}")

    return responses


def compose_digest(
    db_path: str,
    week_str: Optional[str] = None,
    limit: int = 5,
    output_path: Optional[Path] = None,
) -> str:
    """주간 정책브리핑 다이제스트 마크다운 생성.

    Args:
        db_path: announcements.db 경로
        week_str: ISO 주 표기 (기본: 현재 주, 예: "2026-W13")
        limit: 최대 항목 수 (기본: 5)
        output_path: 출력 파일 경로. None이면 반환값만 사용

    Returns:
        생성된 마크다운 텍스트
    """
    # 현재 주 결정
    if week_str is None:
        today = datetime.now()
        week_num = today.isocalendar()[1]
        year = today.isocalendar()[0]
        week_str = f"{year}-W{week_num:02d}"

    week_start, week_end = get_week_date_range(week_str)

    # DB 연결
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # 최근 7일(week_end 기준)의 항목 조회
    seven_days_ago = datetime.fromisoformat(week_end).date() - timedelta(days=6)

    cursor.execute(
        """
        SELECT id, source, title, summary, url, author, period_end, relevance_score
        FROM announcements
        WHERE DATE(created_at) >= ?
        ORDER BY relevance_score DESC
        LIMIT ?
        """,
        (seven_days_ago.isoformat(), limit * 2)  # 버퍼로 2배 조회
    )

    rows = cursor.fetchall()
    conn.close()

    # 섹션별로 분류
    sections = {
        "산림": [],
        "지원사업": [],
        "사회연대경제": [],
    }

    for row in rows:
        item_id, source, title, summary, url, author, period_end, score = row
        category = categorize_item(source, title)

        # 섹션별 항목 수 제한 (limit 합산)
        total_items = sum(len(v) for v in sections.values())
        if total_items >= limit:
            break

        sections[category].append({
            "id": item_id,
            "source": source,
            "title": title,
            "summary": summary or "",
            "url": url,
            "author": author or "",
            "period_end": period_end or "",
            "score": score,
        })

    # 회원사 동정 로드
    form_responses = load_form_responses()

    # 마크다운 생성
    lines = [
        f"<!-- generated by alert.digest.composer at {datetime.now().isoformat()} -->",
        f"<!-- lane: Codex(gpt-5.6) -->",
        "",
        f"# 협의회 주간 정책브리핑 {week_str}",
        f"",
        f"**기간:** {week_start} ~ {week_end}",
        f"",
    ]

    # 산림 정책 동향
    lines.append("## 산림 정책 동향")
    lines.append("")
    if sections["산림"]:
        for item in sections["산림"]:
            lines.extend(_format_item(item))
            lines.append("")
    else:
        lines.append("*(항목 없음)*")
        lines.append("")

    # 지원사업 공고
    lines.append("## 지원사업 공고")
    lines.append("")
    if sections["지원사업"]:
        for item in sections["지원사업"]:
            lines.extend(_format_item(item))
            lines.append("")
    else:
        lines.append("*(항목 없음)*")
        lines.append("")

    # 사회연대경제 동향
    lines.append("## 사회연대경제 동향")
    lines.append("")
    if sections["사회연대경제"]:
        for item in sections["사회연대경제"]:
            lines.extend(_format_item(item))
            lines.append("")
    else:
        lines.append("*(항목 없음)*")
        lines.append("")

    # 회원사 동정
    lines.append("## 회원사 동정")
    lines.append("")
    if form_responses:
        for company, contents in sorted(form_responses.items()):
            lines.append(f"**{company}**")
            for content in contents:
                lines.append(f"- {content}")
            lines.append("")
    else:
        lines.append("*(항목 없음)*")
        lines.append("")

    # 협의회 의견 (마커만)
    lines.append("## 협의회 의견")
    lines.append("")
    lines.append("<!-- 상민 확정 필요 -->")
    lines.append("")

    markdown = "\n".join(lines)

    # 파일 저장
    if output_path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(markdown)

    return markdown


def _format_item(item: Dict) -> List[str]:
    """항목을 마크다운 형식으로 포맷.

    Args:
        item: 공고 항목 딕셔너리

    Returns:
        마크다운 줄 리스트
    """
    lines = []
    lines.append(f"### {item['title']}")
    lines.append("")
    lines.append(f"**기관:** {item['author']}")

    if item['period_end']:
        lines.append(f"**마감:** {item['period_end']}")

    lines.append(f"**원문:** [{item['url']}]({item['url']})")
    lines.append("")

    # 요약 (최대 3줄)
    if item['summary']:
        summary = item['summary'].strip()
        lines.append(f"{summary}")

    return lines
